"""fix birthday_date and created_at updated_at

Revision ID: 13b7c61bd585
Revises: 89adaa556012
Create Date: 2026-04-13 22:28:14.328714

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "13b7c61bd585"
down_revision: Union[str, Sequence[str], None] = "89adaa556012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_accounts",
        "birthday",
        existing_type=sa.VARCHAR(),
        type_=sa.DATE(),
        nullable=True,
        postgresql_using="birthday::date",  # ✅ thêm dòng này
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_accounts",
        "birthday",
        existing_type=sa.DATE(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
