"""add_birthday_user_acoounts

Revision ID: 50c365c5ab44
Revises: 34966f4de502
Create Date: 2026-04-13 02:26:10.625133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50c365c5ab44'
down_revision: Union[str, Sequence[str], None] = '34966f4de502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'reviews', ['uid'])
    op.create_unique_constraint(None, 'user_accounts', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_accounts', type_='unique')
    op.drop_constraint(None, 'reviews', type_='unique')
    # ### end Alembic commands ###
