"""add_books_table

Revision ID: c3c6a80749a3
Revises: 13b7c61bd585
Create Date: 2026-04-16 11:36:31.528761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c3c6a80749a3"
down_revision: Union[str, Sequence[str], None] = "13b7c61bd585"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - create books table."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
